import pandas as pd

df = pd.read_csv('data/raw/zomato.csv', encoding='latin-1')
print('duplicates (full row):', df.duplicated().sum())
print('duplicate url:', df['url'].duplicated().sum())
print()
print('online_order:', df['online_order'].unique())
print('book_table:', df['book_table'].unique())
print('listed_in(type):', df['listed_in(type)'].unique())
print()
print('rest_type sample:', df['rest_type'].dropna().unique()[:15])
print('rest_type nunique:', df['rest_type'].nunique())
print()
print('cost sample:', df['approx_cost(for two people)'].dropna().unique()[:15])
print()
print('cuisines sample:', df['cuisines'].dropna().unique()[:10])
print()
print('rate value counts top:\n', df['rate'].value_counts().head(10))
print()
print('location sample:', df['location'].dropna().unique()[:10])
print('listed_in(city) sample:', df['listed_in(city)'].dropna().unique())
