"""
Zomato Bangalore — Data Cleaning Pipeline
Reads data/raw/zomato.csv, produces data/cleaned/zomato_cleaned.csv
plus a cleaning log written to docs/03_data_cleaning_log.md (counts only,
appended by this script run).
"""
import pandas as pd
import numpy as np

RAW_PATH = "data/raw/zomato.csv"
OUT_PATH = "data/cleaned/zomato_cleaned.csv"

log = []


def step(msg):
    print(msg)
    log.append(msg)


step("=== Zomato Data Cleaning Pipeline ===")

df = pd.read_csv(RAW_PATH, encoding="latin-1")
step(f"Loaded raw data: {df.shape[0]:,} rows x {df.shape[1]} columns")

# 1. Drop columns not needed for the core analytical model
drop_cols = ["phone", "menu_item", "reviews_list", "url" + "" if False else "dish_liked"]
# Keep url as ID, dish_liked dropped from core model (too sparse), phone/menu_item/reviews_list dropped
cols_to_drop = ["phone", "menu_item", "reviews_list", "dish_liked"]
df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])
step(f"Dropped low-value columns: {cols_to_drop}")

# 2. Rename columns to clean snake_case
df = df.rename(columns={
    "approx_cost(for two people)": "cost_for_two",
    "listed_in(type)": "listing_type",
    "listed_in(city)": "listing_city",
    "rate": "rating_raw",
})
step("Renamed columns to snake_case")

# 3. Clean rating column: '4.1/5' -> 4.1 ; 'NEW' / '-' / NaN -> NaN
def parse_rating(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip()
    if x in ("NEW", "-"):
        return np.nan
    if "/" in x:
        x = x.split("/")[0].strip()
    try:
        return float(x)
    except ValueError:
        return np.nan

df["rating"] = df["rating_raw"].apply(parse_rating)
n_new = (df["rating_raw"].astype(str).str.strip() == "NEW").sum()
step(f"Parsed 'rating' from 'rating_raw'. {n_new:,} rows were 'NEW' (no rating yet) -> NaN")
df = df.drop(columns=["rating_raw"])

# 4. Clean cost_for_two: remove commas, cast to numeric
df["cost_for_two"] = (
    df["cost_for_two"].astype(str).str.replace(",", "", regex=False)
)
df["cost_for_two"] = pd.to_numeric(df["cost_for_two"], errors="coerce")
step("Cleaned 'cost_for_two': removed thousand separators, cast to numeric")

# 5. Standardize Yes/No flags to boolean-ish Yes/No (already clean) -> keep as categorical
df["online_order"] = df["online_order"].astype(str).str.strip()
df["book_table"] = df["book_table"].astype(str).str.strip()

# 6. Derive primary_cuisine and primary_rest_type (first listed value)
df["cuisines"] = df["cuisines"].astype("string")
df["primary_cuisine"] = df["cuisines"].str.split(",").str[0].str.strip()

df["rest_type"] = df["rest_type"].astype("string")
df["primary_rest_type"] = df["rest_type"].str.split(",").str[0].str.strip()
step("Derived 'primary_cuisine' and 'primary_rest_type' from multi-valued fields")

# 7. Clean text fields: strip whitespace
for c in ["name", "address", "location", "listing_city", "listing_type"]:
    df[c] = df[c].astype("string").str.strip()

# 8. Flag true duplicate restaurants vs. repeated listing rows (by design, see docs/02)
df["is_unique_restaurant"] = ~df.duplicated(subset=["name", "address"], keep="first")
n_unique = df["is_unique_restaurant"].sum()
step(f"Flagged unique restaurants (by name+address): {n_unique:,} of {len(df):,} rows")

# 9. Derived buckets for analysis
def rating_band(r):
    if pd.isna(r):
        return "Not Rated"
    if r >= 4.0:
        return "Excellent (4.0+)"
    if r >= 3.5:
        return "Good (3.5-3.9)"
    if r >= 3.0:
        return "Average (3.0-3.4)"
    return "Poor (<3.0)"

df["rating_band"] = df["rating"].apply(rating_band)

def cost_bucket(c):
    if pd.isna(c):
        return "Unknown"
    if c < 300:
        return "Budget (<300)"
    if c < 600:
        return "Mid (300-599)"
    if c < 1000:
        return "Premium (600-999)"
    return "Luxury (1000+)"

df["cost_bucket"] = df["cost_for_two"].apply(cost_bucket)
step("Created 'rating_band' and 'cost_bucket' derived dimensions")

# 10. Drop rows with no location at all (unusable for geo analysis) — very small count
before = len(df)
df = df.dropna(subset=["location"])
step(f"Dropped {before - len(df):,} rows with null 'location'")

# 11. Final null audit
nulls = df.isna().sum()
nulls = nulls[nulls > 0]
step("Remaining nulls by column:\n" + nulls.to_string())

# 12. Save cleaned dataset (UTF-8)
df.to_csv(OUT_PATH, index=False, encoding="utf-8")
step(f"Saved cleaned dataset: {OUT_PATH} ({df.shape[0]:,} rows x {df.shape[1]} columns)")

# Write log
with open("docs/03_data_cleaning_log.md", "w", encoding="utf-8") as f:
    f.write("# 03 - Data Cleaning Log\n\n")
    f.write("Auto-generated by `scripts/01_clean_data.py`. Run this script to reproduce.\n\n")
    f.write("## Steps executed\n\n")
    for line in log:
        f.write(f"- {line}\n")
    f.write("\n## Output\n\n")
    f.write(f"- Cleaned file: `{OUT_PATH}`\n")
    f.write(f"- Final shape: {df.shape[0]:,} rows x {df.shape[1]} columns\n")

print("\nDone. Cleaning log written to docs/03_data_cleaning_log.md")
